homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 51.55
  longitude: -0.222
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 22
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/London

# Show links to resources in log and frontend
frontend:
config:
http:
updater:
conversation:
history:
logbook:
sun:

automation: !include automations.yaml
script: !include scripts.yaml

camera:
  - platform: rpi_camera
    vertical_flip: 1

sensor:
  platform: pan_tilt_phat

group:
  default_view:
    view: yes
    icon: mdi:home
    entities:
      - camera.raspberry_pi_camera
      - group.sensors_group

  sensors_group:
    name: Sensors
    entities:
      - sensor.pan_tilt_phat
